spring.application.name=unicobros
server.port=8090

# Logging configuration
logging.level.org.springframework=INFO
logging.level.net.iterart.unicobros=DEBUG
logging.file.name=logs/unicobros.log
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %msg%n
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n

# Database configuration
spring.datasource.url=jdbc:mysql://localhost:3306/unicobros_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=unicobros_user
spring.datasource.password=securepassword
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# Thymeleaf configuration
spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html

# Unicobros API configuration
unicobros.api.key=zJ8LFTBX6Ba8D611e9io13fDZAwj0QmKO1Hn1yIj
unicobros.api.access-token=d31f0721-2f85-44e7-bcc6-15e19d1a53cc
unicobros.api.url=https://api.unicobros.com.ar
